# Generated by Django 3.2.25 on 2024-05-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_pet', models.CharField(max_length=50)),
                ('appointment', models.DateField(blank=True, null=True)),
                ('time', models.DateField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
            ],
        ),
    ]
