# Generated by Django 3.2.25 on 2024-05-20 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('oclock', models.CharField(choices=[("10:00 o'clock", "10:00 o'clock"), ("11:00 o'clock", "11:00 o'clock"), ("12:00 o'clock", "12:00 o'clock"), ("09:00 o'clock", "9:00 o'clock"), ("8:00 o'clock", "8:00 o'clock"), ("13:00 o'clock", "13:00 o'clock"), ("14:00 o'clock", "14:00 o'clock")], max_length=14)),
                ('text', models.TextField(blank=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
