# Generated by Django 3.2.25 on 2024-05-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='appointment',
            new_name='date',
        ),
    ]
