# Generated by Django 3.2.25 on 2024-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.CharField(choices=[('14:00', '14:00'), ('8:00', '8:00'), ('13:00', '13:00'), ('10:00', '10:00'), ('09:00', '9:00'), ('11:00', '11:00'), ('12:00', '12:00')], max_length=7),
        ),
    ]
