# Generated by Django 3.2.25 on 2024-05-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_patient_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='full_name',
        ),
    ]
