# Generated by Django 3.2.25 on 2024-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240516_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.CharField(choices=[('09:00', '9:00'), ('8:00', '8:00'), ('11:00', '11:00'), ('14:00', '14:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('10:00', '10:00')], max_length=7),
        ),
    ]
