# Generated by Django 3.2.25 on 2024-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_userinfo_oclock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='oclock',
            field=models.CharField(choices=[("13:00 o'clock", "13:00 o'clock"), ("11:00 o'clock", "11:00 o'clock"), ("14:00 o'clock", "14:00 o'clock"), ("8:00 o'clock", "8:00 o'clock"), ("12:00 o'clock", "12:00 o'clock"), ("09:00 o'clock", "9:00 o'clock"), ("10:00 o'clock", "10:00 o'clock")], max_length=14),
        ),
    ]
