# Generated by Django 3.2.25 on 2024-05-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_userinfo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='accepted',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('8:00', '8:00'), ('09:00', '9:00')], max_length=7),
        ),
    ]
