# Generated by Django 3.2.25 on 2024-05-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='oclock',
            field=models.CharField(choices=[("8:00 o'clock", "8:00 o'clock"), ("09:00 o'clock", "9:00 o'clock"), ("10:00 o'clock", "10:00 o'clock"), ("11:00 o'clock", "11:00 o'clock"), ("12:00 o'clock", "12:00 o'clock"), ("13:00 o'clock", "13:00 o'clock"), ("14:00 o'clock", "14:00 o'clock")], max_length=20),
        ),
    ]
