# Generated by Django 3.2.25 on 2024-05-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='oclock',
            field=models.CharField(blank=True, choices=[("8:00 o'clock", "8:00 o'clock"), ("09:00 o'clock", "9:00 o'clock"), ("10:00 o'clock", "10:00 o'clock"), ("11:00 o'clock", "11:00 o'clock"), ("12:00 o'clock", "12:00 o'clock"), ("13:00 o'clock", "13:00 o'clock"), ("14:00 o'clock", "14:00 o'clock")], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pet_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
