# Generated by Django 3.2.25 on 2024-05-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-date', '-oclock']},
        ),
    ]
