# Generated by Django 3.2.25 on 2024-05-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['date', 'oclock']},
        ),
    ]
